### PR TITLE
jobs: Add nemu jobs for the different kata repos

### PR DESCRIPTION
**Pull request by chavafg**
Nemu jobs for agent, proxy, runtime, shim and tests
repositories.

Fixes: #130.

Signed-off-by: Salvador Fuentes <salvador.fuentes@intel.com>

### CODE REVIEW

**Comment by chavafg** [comment]
@jodh-intel I think for the moment this is ok since I understand this is going to be used only for the `virtio-fs` integration and our default hypervisor continues to be `qemu`.
@sboeuf wdyt?

**Comment by sboeuf** [comment]
@jodh-intel 
>My only concern is that we're only testing this on Ubuntu. But given the number of test "dimensions" we're having to deal with in Kata, that might be all we can afford to do (time wise and machine resource wise).

Yes I think we cannot afford for this early support to start full steam with a whole duplicated CI. Ubuntu will be just fine as a starter. And let's keep in mind that long term, this feature will be part of Kata, hence no need for a specific CI for it.

**Comment by chavafg** [comment]
ping @kata-containers/ci

**Comment by sboeuf** [comment]
@chavafg cool! Are we ready to run nemu CI everywhere now?

**Pull request merged**
