### PR TITLE
Add CI scripts

### PR DESCRIPTION
**Pull request by jodh-intel**
Add a basic set of CI scripts so that static analysis checks are performed on PRs in this repo.

Also, add a Travis configuration file. Note that language is set to `go` so that `golang` will be installed automatically (since it is required by the `.ci/*` scripts).

Fixes: #197.

Signed-off-by: James O. D. Hunt <james.o.hunt@intel.com>

### CODE REVIEW

**Comment by jodh-intel** [comment]
Yep - the spell checker is only passed markdown files. But regarding XML, I thought about that as I put this PR together and came up with https://github.com/kata-containers/tests/pull/1784.

**Comment by chavafg** [comment]
I've just enabled the CI repo on travis, but still don't see anything triggered... @jodh-intel can you re-push to see if that triggers a run?

**Comment by jodh-intel** [comment]
Thanks @chavafg. Branch re-pushed.

**Comment by chavafg** [comment]
cool, thanks, now travis is running :)

**Pull request merged**
