### PR TITLE
aarch64: online k8s integration tests on AArch64

### PR DESCRIPTION
**Pull request by Pennyzct**
Hi guys
For now, k8s integration tests should be working well on aarch64. Have tested it on my local machine. ;).
So, Could we enable the tests on `arm_slave_02`, which has better performance than `arm_slave_01`.
Also, we only support `k8s + cri-o` for now, `containerd-crio` is still unstable. 😥. working on it.
And plz disable `TEST_CRIO`, to skip the `cri-o` tests.

### CODE REVIEW

**Comment by Pennyzct** [comment]
@jodh-intel @grahamwhaley @chavafg

**Comment by grahamwhaley** [comment]
Docs change lgtm. I'm not sure how we'd enable the k8s test only on `arm_slave_02` and not `arm_slave_01` though. I'm not sure our CI has that ability (to filter test on individual arch/distro nodes). I suspect the easiest/best route is to either turn off `arm_slave_02`, or possibly re-install it with a different distro?, and then we could filter the test by arch/distro, *and* have a second arch for ARM?

**Comment by chavafg** [comment]
@Pennyzct do you think we can run the k8s tests also on the `arm_slave_01`, I think we wont have a problem if it takes a little bit longer... or do you think some tests might fail?

**Comment by Pennyzct** [comment]
Hi~ guys.
@chavafg @grahamwhaley 
Sorry for the trouble. Let's test it on both machine. 😋
I'm just afraid that it may cost more time than `arm_slave_02`, since `arm_slave_01` is quite a old generation.
Never mind, I've calculated the execution time of running all k8s test cases on my local aarch64, around 12min, guessing it won't cause too much liability. ;).
I have raised another [PR](https://github.com/kata-containers/tests/pull/2115) to officially turn it on aarch64.

**Comment by GabyCT** [comment]
The k8s tests has been enabled on ARM so we can merge this.

**Pull request merged**
