### PR TITLE
jenkins: Update configuration files

### LINKED ISSUE #409: update jenkins configuration files

### PR DESCRIPTION
**Pull request by GabyCT**
This PR updates the jenkins configuration files. This is a periodic sync with the jenkins config files into git.

Fixes #409

Signed-off-by: Gabriela Cervantes <gabriela.cervantes.tellez@intel.com>

### CODE REVIEW

**Review by devimc — APPROVED** [review]
thanks @GabyCT

**Review by jodh-intel — COMMENTED** [review]
Hi @GabyCT - this is a huge change with lots of almost-impossible-to-review XML (and what looks like XHTML embedded in XML) but there is no detail on the changes on this PR.

If this is just the usual periodic "sync the Jenkins config files into git", please state this on the PR and the issue. Alternatively, if it's something else, again, please state this on the PR :smile:

**Comment by GabyCT** [comment]
@jodh-intel yes it is a periodic sync the jenkins config files into git

**Review by jodh-intel — APPROVED** [review]
ok, thanks @GabyCT.

lgtm

**Pull request merged**
