### PR TITLE
jenkins: Remove old jenkins jobs for kata 1.x

### LINKED ISSUE #381: remove old jenkins jobs for kata 1.x

### PR DESCRIPTION
**Pull request by GabyCT**
This PR removes the jenkins jobs configs that were used in kata 1.x.

Fixes #381

Signed-off-by: Gabriela Cervantes <gabriela.cervantes.tellez@intel.com>

### CODE REVIEW

**Comment by GabyCT** [comment]
@fidencio could you please take a look into this PR? this is part of the work of cleaning old CI jobs thanks

**Comment by fidencio** [comment]
Will do by the end of this week, @GabyCT!

**Review by devimc — APPROVED** [review]

**Comment by fidencio** [comment]
I'm adding the `do-not-merge` label so I have the chance to go through this in the next days.

**Comment by fidencio** [comment]
@GabyCT, I finally had the time to go through this one, sorry the time it took.

Let's see the jobs that don't remove:
```
fidencio@quino ~/go/src/github.com/kata-containers/ci/jenkins/jobs $ ls
cloud-hypervisor-nightly-x86_64
image-nightly-x86_64
kata-baremetal-containerd-k8s-conformance-e2e
kata-baremetal-stability-testing
kata-containers-2.0-centos-PR
kata-containers-2.0-clh-crio-ubuntu-PR
kata-containers-2.0-containerd-k8s-conformance-e2e
kata-containers-2.0-debian-PR
kata-containers-2.0-fedora-PR
kata-containers-2.0-fedora-PR-crio-k8s-e2e-minimal
kata-containers-2.0-firecracker-ubuntu-PR
kata-containers-2.0-metrics-ubuntu-20-04-PR
kata-containers-2.0-runtime-ubuntu-PR-containerd-k8s-minimal
kata-containers-2.0-tests-centos-PR
kata-containers-2.0-tests-clh-crio-ubuntu-PR
kata-containers-2.0-tests-debian-PR
kata-containers-2.0-tests-fedora-PR
kata-containers-2.0-tests-fedora-PR-crio-k8s-e2e-complete
kata-containers-2.0-tests-fedora-PR-crio-k8s-e2e-minimal
kata-containers-2.0-tests-firecracker-ubuntu-P
kata-containers-2.0-tests-metrics-ubuntu-20-04-PR
kata-containers-2.0-tests-ubuntu20.04-PR
kata-containers-2.0-tests-ubuntu-ARM-PR
kata-containers-2.0-tests-ubuntu-clh-virtiofs-PR
kata-containers-2.0-tests-ubuntu-initrd-PR
kata-containers-2.0-tests-ubuntu-PR
kata-containers-2.0-tests-ubuntu-PR-clh-containerd-k8s-minimal
kata-containers-2.0-tests-ubuntu-PR-containerd-k8s-minimal
kata-containers-2.0-tests-vfio-PR
kata-containers-2.0-ubuntu-20.04-PR
kata-containers-2.0-ubuntu-ARM-PR
kata-containers-2.0-ubuntu-initrd-PR
kata-containers-2.0-ubuntu-PR
kata-containers-2.0-ubuntu-PR-clh-containerd-k8s-minimal
kata-containers-2.0-ubuntu-PR-containerd-k8s-minimal
kata-containers-2.0-vfio-PR
kata-containers-containerd-k8s-conformance-e2e
kata-containers-crio-k8s-conformance-e2e
kata-containers-crio-PR
kata-containers-tests-cloud-hypervisor-k8s-e2e-containerd
kata-containers-tests-cloud-hypervisor-k8s-e2e-crio
kata-containers-tests-cri-containerd-PR
kata-containers-tests-ubuntu-18-04-virtiofs-PR
kata-containers-tests-ubuntu-PR-cloud-hypeprvisor-k8s-containerd
kata-containers-tests-ubuntu-PR-cloud-hypeprvisor-k8s-crio
kata-containers-tests-ubuntu-PR-cloud-hypeprvisor-k8s-e2e-containerd-full
kata-containers-tests-ubuntu-PR-cloud-hypeprvisor-k8s-e2e-containerd-minimal
kata-containers-tests-ubuntu-PR-cloud-hypeprvisor-k8s-e2e-containerd-shimv2-minimal
kata-containers-tests-ubuntu-PR-cloud-hypeprvisor-k8s-e2e-crio-full
kata-containers-tests-ubuntu-PR-cloud-hypeprvisor-k8s-e2e-crio-minimal
kata-containers-tests-ubuntu-PR-cloud-hypeprvisor-minimal
kata-containers-tests-ubuntu-PR-containerd-k8s-complete
kernel-experimental-nightly-x86_64
kernel-nightly-x86_64
metrics-reboot-ubuntu-16.04-slave
qemu-experimental-nightly-x86_64
qemu-nightly-x86_64
release
```

Do we need to maintain all of those? I'd recommend to go through the not removed ones and check whether they still make sense.

I can see at least one job that we have that's not there, and that's my fault: http://jenkins.katacontainers.io/job/kata-containers-2-crio-PR/
And that one replaced kata-containers-crio-PR

**Comment by GabyCT** [comment]
@fidencio at least metrics-reboot-ubuntu-16.04-slave is still needed, the rest I am not sure as I did not enable them. I do not want to remove something that I did not do it. I believe that some of the `kata-containers-tests-ubuntu-PR-cloud-hypeprvisor-k8s-e2e-containerd-full` and so on are used in kata 2.0.

**Comment by GabyCT** [comment]
I think we can start removing these and I can open an issue in order to track the rest...because I need to ask if it is still use or not

**Comment by fidencio** [comment]
> I think we can start removing these and I can open an issue in order to track the rest...because I need to ask if it is still use or not

Totally, let's go ahead and have this one merged and work on the others.

**Review by fidencio — APPROVED** [review]
lgtm, thanks @GabyCT!

**Pull request merged**
