### PR TITLE
github: delete the porting labels workflow

### LINKED ISSUE #421: Delete the PR porting labels checking
We don't have branches on this repository therefore we don't need the porting labels checking.

### PR DESCRIPTION
**Pull request by wainersm**
It does't need to back/forward port pull requests on this repository as
we solely work on 'main'. Therefore, the porting labels checking should
not be executed.

Fixes #421
Signed-off-by: Wainer dos Santos Moschetta <wainersm@redhat.com>

### CODE REVIEW

**Review by fidencio — APPROVED** [review]
lgtm, thanks @wainersm!
Let me make this non-mandatory on the settings side.

**Comment by fidencio** [comment]
> lgtm, thanks @wainersm! Let me make this non-mandatory on the settings side.

It's not even mandatory on the GitHub side.
While here, why do we have golang stsatic checks on this repo?

**Comment by wainersm** [comment]
> > lgtm, thanks @wainersm! Let me make this non-mandatory on the settings side.
> 
> It's not even mandatory on the GitHub side. While here, why do we have golang stsatic checks on this repo?

They seems not required too... I will send a follow up PR. Thanks for reviewing!

**Comment by wainersm** [comment]
> > lgtm, thanks @wainersm! Let me make this non-mandatory on the settings side.
> 
> It's not even mandatory on the GitHub side. While here, why do we have golang stsatic checks on this repo?

#427

**Pull request merged**
