### PR TITLE
jenkins: Add s390x tests job

### PR DESCRIPTION
**Pull request by Jakob-Naucke**
following #388; Ubuntu 20.04, image, containerd, already running at
http://jenkins.katacontainers.io/job/kata-containers-2.0-tests-ubuntu-s390x-PR/

Fixes: #390
Signed-off-by: Jakob Naucke <jakob.naucke@ibm.com>

### CODE REVIEW

**Review by GabyCT — APPROVED** [review]

**Comment by Jakob-Naucke** [comment]
rebased without changes to re-trigger porting labels check

**Review by jodh-intel — APPROVED** [review]
`<omg_xml_makes_my_eyes_bleed need_yaml="true">lgtm!</omg_xml_makes_my_eyes_bleed>`

**Comment by Jakob-Naucke** [comment]
@jodh-intel you could also double check the XML matches and then review the build config in the web GUI instead :)

**Comment by jodh-intel** [comment]
@Jakob-Naucke - sure. My silly comment was unrelated to this PR, I'd just love to see @wainersm's #359 land as a simple YAML file beats an unwieldy XML file any day imho ;)

**Pull request merged**
