### PR TITLE
ci: Add test Matrix

### PR DESCRIPTION
**Pull request by chavafg**
This test matrix shows the different configuration,
architectures and tests that we run in each of our jobs.

Fixes: #145.

Signed-off-by: Salvador Fuentes <salvador.fuentes@intel.com>

### CODE REVIEW

**Comment by gnawux** [comment]
Awesome job! I like this matrix

**Comment by grahamwhaley** [comment]
/me resists pressing the big green button and gives @alicefr @nitkon a chance to respond...

**Comment by chavafg** [comment]
@jodh-intel I didn't link to an xml file because we have one xml file per repository job, addressed the other comments. 
@grahamwhaley I think for s390x and Power8 we reflect the current state, as soon as we increase coverage in those platforms, we can update the table.

**Comment by alicefr** [comment]
@grahamwhaley I'm working on cri-containerd and I'll update the other rows. I guess it should be consistent with the https://github.com/kata-containers/tests/blob/master/.ci/s390x/configuration_s390x.yaml

**Comment by grahamwhaley** [comment]
Thanks @alicefr - tbh, I'd totally forgotten (or not really registered in my head) those yaml files :-) It should also be consistent with what is configured in the jenkins jobs for s390 on the jenkins server.... which, normally I'd say we can see as the xml over at https://github.com/kata-containers/ci/tree/master/jenkins/jobs - but, it looks like we have not uploaded any of the s390 xml config files there - @GabyCT , is that something you can PR? (/cc @chavafg , also @Pennyzct for ARM and @nitkon for Power8 similarly I think).

**Comment by GabyCT** [comment]
@grahamwhaley done https://github.com/kata-containers/ci/pull/151 :)

**Pull request merged**
