### PR TITLE
Remove skopeo jobs

### PR DESCRIPTION
**Pull request by stevenhorsman**

### CODE REVIEW

**Review by fidencio — DISMISSED** [review]
lgtm, thanks @stevenhorsman!

**Comment by wainersm** [comment]
@stevenhorsman could you hold on this PR for a few hours? I am working on a way to also delete the jobs automatically.

**Comment by wainersm** [comment]
ok, need to merge https://github.com/kata-containers/ci/pull/524 , rebase this PR and add the list of jobs to be delete in the trash file. Hopefully it will work out :D

**Comment by stevenhorsman** [comment]
@wainersm - I think I've done it correctly, so it's ready for you to take a look. Thanks!

**Review by wainersm — APPROVED** [review]
Thanks @stevenhorsman !

**Comment by wainersm** [comment]
ah, @stevenhorsman , as I mentioned on private, on merging this PR the jobs will get `REGISTRY_CREDENTIAL_ENCODED` not exported. I am working on a PR to make that configuration on the jobs-builder, I should send it soon after testing locally.

**Review by fidencio — APPROVED** [review]
lgtm, thanks @stevenhorsman!

**Pull request merged**
