### PR TITLE
Bootstrap repo

### PR DESCRIPTION
**Pull request by jodh-intel**
- Add the pullapprove configuration file.
- Add the standard Code of Conduct and contributing docs.

### CODE REVIEW

**Comment by egernst** [comment]
lgtm - thanks @jodh-intel

**Comment by jodh-intel** [comment]
Let's see if I can self-approve as this is what github is asking me to do...

**Comment by jodh-intel** [comment]
lgtm

**Comment by jodh-intel** [comment]
Nope - let's play hardball then...

**Pull request merged**
